apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recipe-app.backendContainer" . }}
  labels:
    {{- include "recipe-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "recipe-app.selectorLabels" . | nindent 6 }}
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    #Have not defined podAnnotations and podLabels in values.yaml yet
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "recipe-app.labels" . | nindent 8 }}
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
# Setting up the backend container 
      containers:
        - name: {{ include "recipe-app.backendContainer" . }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.backendRepository }}:{{ .Values.image.tag  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-port
              # This is the port that the backend container listens on
              containerPort: {{ .Values.service.backendPort }}
              protocol: TCP
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }} 
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        
        
    
---
# Setting up the frontend container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recipe-app.frontendContainer" . }}
  labels:
    {{- include "recipe-app.labels" . | nindent 4 }}
    
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "recipe-app.selectorLabels" . | nindent 6 }}
      {{- include "frontend.selectorLabels" . | nindent 6 }}
      
    {{/* 
      The frontend container is the one that serves the user interface
    */}}  
  template:
    metadata:

      labels:
        {{- include "recipe-app.labels" . | nindent 8 }}
        {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "recipe-app.frontendContainer" . }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.frontendRepository }}:{{ .Values.image.tag  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-port
              # This is the port that the frontend container listens on
              containerPort: {{ .Values.service.frontendPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
            
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      
