apiVersion: v1 
kind: Service
metadata:
  name: {{ include "recipe-app.fullname" .}}
  labels:
    {{- include "recipe-app.labels" . | nindent 4 }}
spec:
  selector:
   {{- include "recipe-app.selectorLabels" . | nindent 4 }}
  ports:  
    - port: 80 
      targetPort: {{ .Values.service.frontendPort }} 
      protocol: TCP 
  type: {{ .Values.service.type }}
  