apiVersion: v1 
kind: Service
metadata:
  name: {{ include "recipe-app.fullname" .}}
  labels:
    {{- include "recipe-app.labels" . | nindent 4 }}
spec:
  selector:
   {{- include "frontend.selectorLabels" . | nindent 4 }}
  ports:  
    - port: 80 
      name: http
      targetPort: {{ .Values.service.frontendPort }} 
      protocol: TCP 
      # nodePort: 32160
  type: LoadBalancer

  
  

--- 
{{ if .Values.ingress.enabled }}
# Setting up the Ingress resource
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "recipe-app.fullname" .}} 
spec:
  ingressClassName: nginx 
  rules:
  - host: 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-node
            port:
              number: 80 
{{- end }}
