# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: default
  labels:
    app: frontend-app
spec:
  selector:
    matchLabels:
      app: frontend-app
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: charido-app
        image: anamskenneth/next_js_aws_devop_project_frontend:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5173
          name: charido-port
        volumeMounts:
        - name: mainapp
          mountPath: /etc/charido
      volumes:
        - name: mainapp
          # hostPath:
          #   path: ./main-app
      # restartPolicy: Always
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: default
  labels:
    app: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: anamskenneth/next_js_aws_devop_project_backend:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5173
          name: charido-port
        volumeMounts:
        - name: mainapp
          mountPath: /etc/online-angels
      volumes:
        - name: mainapp
          # hostPath:
          #   path: ./main-app
      # restartPolicy: Always