# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: charido-app
  namespace: default
  labels:
    app: charido
spec:
  selector:
    matchLabels:
      app: charido
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: charido
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: charido-app
        image: charido
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        # env:
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: myjob
        #       key: DB_HOST
        # - name: DB_HOST
        #   valueFrom:
        #     secretKeyRef:
        #       name: myjob
        #       key: MSSQL_SA_PASSWORD
        ports:
        - containerPort: 3000
          name: charido-port
        volumeMounts:
        - name: main-app
          mountPath: /etc/charido
      volumes:
        - name: main-app
          hostPath:
            path: ./main-app
      # restartPolicy: Always
--- 
