name: ci

on:
  push:
    branches:
      - 'main'

jobs:

  build-push-image:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      #Running security scans on the codebase (NIST, FEDRAMP, OWASP, etc.)
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif' 

      #scanning the IaC files (Kubernetes)
      - name: Scan Kubernetes YAML folder
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'config'
          hide-progress: true
          input: './Helm/*'
          format: 'sarif'
          output: 'trivy-results.sarif'
          # exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Setting up env 
        run: |
          echo "Setting up environment variables"
          echo "CLIENT_URL=${{ secrets.CLIENT_URL }}" >> next_js_aws_devop_project/backend/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >>  next_js_aws_devop_project/backend/.env
          echo "PORT=${{ secrets.PORT}}" >>  next_js_aws_devop_project/backend/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >>  next_js_aws_devop_project/backend/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >>  next_js_aws_devop_project/backend/.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >>  next_js_aws_devop_project/backend/.env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >>  next_js_aws_devop_project/backend/.env

      #Using makefile to run build and push images 
      - name: Building backend image
        run: |
          echo "Building backend image using Makefile"
          make build_backend_image

      - name: Building frontend image
        run: |
          echo "Building frontend image using Makefile"
          make build_frontend_image

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Pushing backend image to DockerHub
        run: |
          echo "Pushing backend image to DockerHub"
          # make docker_login
          make docker_push 
          
      
      # - name: Set up Docker Buildx for demo
      #   uses: docker/setup-buildx-action@v2
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}
      
      # - name: show pwd
      #   run: |
      #     pwd
      #     ls -la next_js_aws_devop_project

        
          
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3 

      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./charido-landing-page/charido-landing-page
      #     file: ./charido-landing-page/charido-landing-page/Dockerfile
      #     push: true
      #     tags: app:latest 