name: ci

on:
  push:
    branches:
      - 'main'

jobs:

  build-push-image:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      
        # name: Set up QEMU for demo
        # uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx for demo
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - 
        name: show pwd
        run: |
          pwd
          ls -la charido-landing-page
          ls -la online-angels-landing-page
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3 

      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./charido-landing-page/charido-landing-page
      #     file: ./charido-landing-page/charido-landing-page/Dockerfile
      #     push: true
      #     tags: app:latest 